[package]
name = "tm_composer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "True Modules: Rust composer (stub)"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "tm-rs-compose"
path = "src/main.rs"
